### ISSUE TITLE
Running 'npm start' failed on Mac

### ISSUE THREAD

**Issue by tingzhao** [quheng/hatu#11]
Running 'npm start' on Mac produced the following error:

> . ./scripts/default_environment.sh && BABEL_ENV=dev babel-node server

loader option has been deprecated - replace with "use"
hatu listening at 0.0.0.0:2222
failed to connect dvid { Error
    at ClientRequest.<anonymous> (/Users/zhaot/Downloads/hatu/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  name: 'FetchError',
  message: 'request to http://localhost:2048/api/repos/info failed, reason: connect ECONNREFUSED 127.0.0.1:2048',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }

**Comment by quheng** [comment]
错误信息是没有连接到 dvid.
 scripts/run_dependencies.sh 会在 docker 里启动一个 dvid, 默认的端口是 2048.
如果已经有了 dvid, 但是地址不是 localhost:2048 的话, 需要在 scripts/default_environment.sh 里面设置一下 dvid 的地址.

**Comment by tingzhao** [comment]
scripts/default_environment.sh用什么格式设置？

**Comment by quheng** [comment]
scripts/default_environment.sh  目前包含了 postgres 和 dvid 的配置. 格式和默认的格式一样就好, 主要是端口和地址.

**Comment by tingzhao** [comment]
我没有其它dvid在跑，还是不行。npm run test没问题。

**Comment by tingzhao** [comment]
docker ps -a输出：
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS                    NAMES
3b9b83e1cc19        flyem/dvid          "/usr/local/bin/dv..."   14 minutes ago      Up 12 seconds               0.0.0.0:2048->8000/tcp   dvid
0bf2b6931d0f        hjwissac/slicedb    "sh"                     14 minutes ago      Exited (0) 13 seconds ago                            slicedb
0c57973ae1bc        postgres            "docker-entrypoint..."   14 minutes ago      Up 13 seconds               0.0.0.0:1024->5432/tcp   pg

**Comment by tingzhao** [comment]
运行docker run --name dvid -p 2048:8000 --volumes-from slicedb flyem/dvid有以下错误：
/usr/local/bin/dvid.sh: line 3: [: !=: unary operator expected

**Comment by quheng** [comment]
这个好像是 dvid 的问题, 但是不影响使用. 可以加上 -d 的参数, 在后台运行就可以了

**Comment by tingzhao** [comment]
问题是dvid好像没启动起来，localhost:2048连不上

**Comment by quheng** [comment]
docker ps -a 的输出显示 dvid 的状态是 UP, 应该是启动起来了
